<?php

use App\Entity\Categories\Car\CarBrand;
use Illuminate\Database\Seeder;

class CarBrandsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CarBrand::create(['name' => 'AC', 'name_ru' => 'АС', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('AC')]);
        CarBrand::create(['name' => 'Acura', 'name_ru' => 'Акура', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Acura')]);
        CarBrand::create(['name' => 'Adler', 'name_ru' => 'Адлер', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Adler')]);
        CarBrand::create(['name' => 'Alfa Romeo', 'name_ru' => 'Альфа-Ромео', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Alfa Romeo')]);
        CarBrand::create(['name' => 'Alpina', 'name_ru' => 'Альпина', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Alpina')]);
        CarBrand::create(['name' => 'Alpine', 'name_ru' => 'Альпине', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Alpine')]);
        CarBrand::create(['name' => 'AM General', 'name_ru' => 'АМ Дженерал', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('AM General')]);
        CarBrand::create(['name' => 'AMC', 'name_ru' => 'АМС', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('AMC')]);
        CarBrand::create(['name' => 'Ariel', 'name_ru' => 'Ариель', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Ariel')]);
        CarBrand::create(['name' => 'Aro', 'name_ru' => 'Аро', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Aro')]);
        CarBrand::create(['name' => 'Asia', 'name_ru' => 'Азия', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Asia')]);
        CarBrand::create(['name' => 'Aston Martin', 'name_ru' => 'Астан Мартин', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Aston Martin')]);
        CarBrand::create(['name' => 'Audi', 'name_ru' => 'Ауди', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Audi')]);
        CarBrand::create(['name' => 'Aurus', 'name_ru' => 'Аурус', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Aurus')]);
        CarBrand::create(['name' => 'Austin', 'name_ru' => 'Аустин', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Austin')]);
        CarBrand::create(['name' => 'Austin Healey', 'name_ru' => 'Аустин Хили', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Austin Healey')]);
        CarBrand::create(['name' => 'Autobianchi', 'name_ru' => 'Autobianchi', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Autobianchi')]);
        CarBrand::create(['name' => 'BAIC', 'name_ru' => 'BAIC', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('BAIC')]);
        CarBrand::create(['name' => 'Bajaj', 'name_ru' => 'Bajaj', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Bajaj')]);
        CarBrand::create(['name' => 'Baltijas Dzips', 'name_ru' => 'Балтияс Дзипс', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Baltijas Dzips')]);
        CarBrand::create(['name' => 'Batmobile', 'name_ru' => 'Бэтмобиль', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Batmobile')]);
        CarBrand::create(['name' => 'Bentley', 'name_ru' => 'Bentley', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Bentley')]);
        CarBrand::create(['name' => 'Bertone', 'name_ru' => 'Bertone', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Bertone')]);
        CarBrand::create(['name' => 'Bilenkin', 'name_ru' => 'Биленкин', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Bilenkin')]);
        CarBrand::create(['name' => 'Bitter', 'name_ru' => 'Биттер', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Bitter')]);
        CarBrand::create(['name' => 'BMW', 'name_ru' => 'БМВ', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('BMW')]);
        CarBrand::create(['name' => 'Borgward', 'name_ru' => 'Borgward', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Borgward')]);
        CarBrand::create(['name' => 'Brabus', 'name_ru' => 'Брабус', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Brabus')]);
        CarBrand::create(['name' => 'Brilliance', 'name_ru' => 'Бриллианс', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Brilliance')]);
        CarBrand::create(['name' => 'Bristol', 'name_ru' => 'Бристоль', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Bristol')]);
        CarBrand::create(['name' => 'Bufori', 'name_ru' => 'Буфори', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Bufori')]);
        CarBrand::create(['name' => 'Bugatti', 'name_ru' => 'Бугати', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Bugatti')]);
        CarBrand::create(['name' => 'Buick', 'name_ru' => 'Buick', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Buick')]);
        CarBrand::create(['name' => 'BYD', 'name_ru' => 'BYD', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('BYD')]);
        CarBrand::create(['name' => 'Byvin', 'name_ru' => 'Byvin', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Byvin')]);
        CarBrand::create(['name' => 'Cadillac', 'name_ru' => 'Катилак', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Cadillac')]);
        CarBrand::create(['name' => 'Callaway', 'name_ru' => 'Каллавай', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Callaway')]);
        CarBrand::create(['name' => 'Carbodies', 'name_ru' => 'Карботис', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Carbodies')]);
        CarBrand::create(['name' => 'Caterham', 'name_ru' => 'Катерхам', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Caterham')]);
        CarBrand::create(['name' => 'Chana', 'name_ru' => 'Chana', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Chana')]);
        CarBrand::create(['name' => 'Changan', 'name_ru' => 'Changan', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Changan')]);
        CarBrand::create(['name' => 'ChangFeng', 'name_ru' => 'ChangFeng', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('ChangFeng')]);
        CarBrand::create(['name' => 'Changhe', 'name_ru' => 'Changhe', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Changhe')]);
        CarBrand::create(['name' => 'Chery', 'name_ru' => 'Чери', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Chery')]);
        CarBrand::create(['name' => 'Chevrolet', 'name_ru' => 'Шевролет', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Chevrolet')]);
        CarBrand::create(['name' => 'Chrysler', 'name_ru' => 'Крайслер', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Chrysler')]);
        CarBrand::create(['name' => 'Citroen', 'name_ru' => 'Ситроен', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Citroen')]);
        CarBrand::create(['name' => 'Cizeta', 'name_ru' => 'Цизита', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Cizeta')]);
        CarBrand::create(['name' => 'Coggiola', 'name_ru' => 'Coggiola', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Coggiola')]);
        CarBrand::create(['name' => 'Cord', 'name_ru' => 'Корд', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Cord')]);
        CarBrand::create(['name' => 'Dacia', 'name_ru' => 'Дациа', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Dacia')]);
        CarBrand::create(['name' => 'Dadi', 'name_ru' => 'Дади', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Dadi')]);
        CarBrand::create(['name' => 'Daewoo', 'name_ru' => 'Деву', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Daewoo')]);
        CarBrand::create(['name' => 'Daihatsu', 'name_ru' => 'Daihatsu', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Daihatsu')]);
        CarBrand::create(['name' => 'Daimler', 'name_ru' => 'Далмер', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Daimler')]);
        CarBrand::create(['name' => 'Datsun', 'name_ru' => 'Датсун', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Datsun')]);
        CarBrand::create(['name' => 'De Tomaso', 'name_ru' => 'Де Томазо', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('De Tomaso')]);
        CarBrand::create(['name' => 'Delage', 'name_ru' => 'Delage', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Delage')]);
        CarBrand::create(['name' => 'DeLorean', 'name_ru' => 'DeLorean', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('DeLorean')]);
        CarBrand::create(['name' => 'Derways', 'name_ru' => 'Derways', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Derways')]);
        CarBrand::create(['name' => 'DeSoto', 'name_ru' => 'DeSoto', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('DeSoto')]);
        CarBrand::create(['name' => 'DKW', 'name_ru' => 'DKW', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('DKW')]);
        CarBrand::create(['name' => 'Dodge', 'name_ru' => 'Доджи', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Dodge')]);
        CarBrand::create(['name' => 'DongFeng', 'name_ru' => 'ДоджФинж', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('DongFeng')]);
        CarBrand::create(['name' => 'Doninvest', 'name_ru' => 'Донинвест', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Doninvest')]);
        CarBrand::create(['name' => 'Donkervoort', 'name_ru' => 'Donkervoort', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Donkervoort')]);
        CarBrand::create(['name' => 'DS', 'name_ru' => 'ДС', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('DS')]);
        CarBrand::create(['name' => 'DW Hower', 'name_ru' => 'DW Hower', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('DW Hower')]);
        CarBrand::create(['name' => 'Eagle', 'name_ru' => 'Эгли', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Eagle')]);
        CarBrand::create(['name' => 'Eagle Cars', 'name_ru' => 'Эгли авто', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Eagle Cars')]);
        CarBrand::create(['name' => 'E-Car', 'name_ru' => 'E-Car', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('E-Car')]);
        CarBrand::create(['name' => 'Excalibur', 'name_ru' => 'Экскалибур', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Excalibur')]);
        CarBrand::create(['name' => 'FAW', 'name_ru' => 'FAW', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('FAW')]);
        CarBrand::create(['name' => 'Ferrari', 'name_ru' => 'Ферари', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Ferrari')]);
        CarBrand::create(['name' => 'Fiat', 'name_ru' => 'Фиат', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Fiat')]);
        CarBrand::create(['name' => 'Fisker', 'name_ru' => 'Fisker', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Fisker')]);
        CarBrand::create(['name' => 'Flanker', 'name_ru' => 'Фланкер', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Flanker')]);
        CarBrand::create(['name' => 'Ford', 'name_ru' => 'Форд', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Ford')]);
        CarBrand::create(['name' => 'Foton', 'name_ru' => 'Фотон', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Foton')]);
        CarBrand::create(['name' => 'FSO', 'name_ru' => 'FSO', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('FSO')]);
        CarBrand::create(['name' => 'Fuqi', 'name_ru' => 'Fuqi', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Fuqi')]);
        CarBrand::create(['name' => 'GAC', 'name_ru' => 'GAC', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('GAC')]);
        CarBrand::create(['name' => 'Geely', 'name_ru' => 'Джели', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Geely')]);
        CarBrand::create(['name' => 'Genesis', 'name_ru' => 'Дженезис', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Genesis')]);
        CarBrand::create(['name' => 'Geo', 'name_ru' => 'Geo', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Geo')]);
        CarBrand::create(['name' => 'GMC', 'name_ru' => 'GMC', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('GMC')]);
        CarBrand::create(['name' => 'Gonow', 'name_ru' => 'Gonow', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Gonow')]);
        CarBrand::create(['name' => 'Gordon', 'name_ru' => 'Гордон', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Gordon')]);
        CarBrand::create(['name' => 'GP', 'name_ru' => 'ГП', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('GP')]);
        CarBrand::create(['name' => 'Great Wall', 'name_ru' => 'Грит Валл', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Great Wall')]);
        CarBrand::create(['name' => 'Hafei', 'name_ru' => 'Hafei', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Hafei')]);
        CarBrand::create(['name' => 'Haima', 'name_ru' => 'Haima', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Haima')]);
        CarBrand::create(['name' => 'Hanomag', 'name_ru' => 'Hanomag', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Hanomag')]);
        CarBrand::create(['name' => 'Haval', 'name_ru' => 'Хавал', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Haval')]);
        CarBrand::create(['name' => 'Hawtai', 'name_ru' => 'Hawtai', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Hawtai')]);
        CarBrand::create(['name' => 'Hindustan', 'name_ru' => 'Индостан', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Hindustan')]);
        CarBrand::create(['name' => 'Hispano-Suiza', 'name_ru' => 'Hispano-Suiza', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Hispano-Suiza')]);
        CarBrand::create(['name' => 'Holden', 'name_ru' => 'Holden', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Holden')]);
        CarBrand::create(['name' => 'Honda', 'name_ru' => 'Хонда', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Honda')]);
        CarBrand::create(['name' => 'Horch', 'name_ru' => 'Horch', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Horch')]);
        CarBrand::create(['name' => 'HuangHai', 'name_ru' => 'Huanghai', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('HuangHai')]);
        CarBrand::create(['name' => 'Hudson', 'name_ru' => 'Гудзон', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Hudson')]);
        CarBrand::create(['name' => 'Hummer', 'name_ru' => 'зуммер', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Hummer')]);
        CarBrand::create(['name' => 'Hyundai', 'name_ru' => 'Хюндай', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Hyundai')]);
        CarBrand::create(['name' => 'Infiniti', 'name_ru' => 'Инфинити', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Infiniti')]);
        CarBrand::create(['name' => 'Innocenti', 'name_ru' => 'Инноченти', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Innocenti')]);
        CarBrand::create(['name' => 'International', 'name_ru' => 'Интернациаонал', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('International')]);
        CarBrand::create(['name' => 'Invicta', 'name_ru' => 'Invicta', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Invicta')]);
        CarBrand::create(['name' => 'Iran Khodro', 'name_ru' => 'Иран Ходро', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Iran Khodro')]);
        CarBrand::create(['name' => 'Isdera', 'name_ru' => 'Isdera', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Isdera')]);
        CarBrand::create(['name' => 'Isuzu', 'name_ru' => 'Isuzu', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Isuzu')]);
        CarBrand::create(['name' => 'JAC', 'name_ru' => 'JAC', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('JAC')]);
        CarBrand::create(['name' => 'Jaguar', 'name_ru' => 'Ягуар', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Jaguar')]);
        CarBrand::create(['name' => 'Jeep', 'name_ru' => 'Джип', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Jeep')]);
        CarBrand::create(['name' => 'Jensen', 'name_ru' => 'Jensen', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Jensen')]);
        CarBrand::create(['name' => 'Jinbei', 'name_ru' => 'Jinbei', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Jinbei')]);
        CarBrand::create(['name' => 'JMC', 'name_ru' => 'JMC', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('JMC')]);
        CarBrand::create(['name' => 'Kia', 'name_ru' => 'Кия', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Kia')]);
        CarBrand::create(['name' => 'Koenigsegg', 'name_ru' => 'Koenigsegg', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Koenigsegg')]);
        CarBrand::create(['name' => 'KTM AG', 'name_ru' => 'КТМ АГ', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('KTM AG')]);
        CarBrand::create(['name' => 'LADA (ВАЗ)', 'name_ru' => 'ЛАДА (ВАЗ)', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('LADA (ВАЗ)')]);
        CarBrand::create(['name' => 'Lamborghini', 'name_ru' => 'Ламборгини', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Lamborghini')]);
        CarBrand::create(['name' => 'Lancia', 'name_ru' => 'Lancia', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Lancia')]);
        CarBrand::create(['name' => 'Land Rover', 'name_ru' => 'Ланд Ровер', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Land Rover')]);
        CarBrand::create(['name' => 'Landwind', 'name_ru' => 'Landwind', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Landwind')]);
        CarBrand::create(['name' => 'Lexus', 'name_ru' => 'Лексус', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Lexus')]);
        CarBrand::create(['name' => 'Liebao Motor', 'name_ru' => 'Liebao Motor', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Liebao Motor')]);
        CarBrand::create(['name' => 'Lifan', 'name_ru' => 'Лифан', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Lifan')]);
        CarBrand::create(['name' => 'Ligier', 'name_ru' => 'Ligier', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Ligier')]);
        CarBrand::create(['name' => 'Lincoln', 'name_ru' => 'Линкольн', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Lincoln')]);
        CarBrand::create(['name' => 'Lotus', 'name_ru' => 'Лотос', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Lotus')]);
        CarBrand::create(['name' => 'LTI', 'name_ru' => 'LTI', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('LTI')]);
        CarBrand::create(['name' => 'Lucid', 'name_ru' => 'Люцид', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Lucid')]);
        CarBrand::create(['name' => 'Luxgen', 'name_ru' => 'Luxgen', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Luxgen')]);
        CarBrand::create(['name' => 'Mahindra', 'name_ru' => 'Mahindra', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Mahindra')]);
        CarBrand::create(['name' => 'Marcos', 'name_ru' => 'Marcos', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Marcos')]);
        CarBrand::create(['name' => 'Marlin', 'name_ru' => 'Marlin', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Marlin')]);
        CarBrand::create(['name' => 'Marussia', 'name_ru' => 'Маруся', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Marussia')]);
        CarBrand::create(['name' => 'Maruti', 'name_ru' => 'Maruti', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Maruti')]);
        CarBrand::create(['name' => 'Maserati', 'name_ru' => 'Мазерати', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Maserati')]);
        CarBrand::create(['name' => 'Maybach', 'name_ru' => 'Майбах', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Maybach')]);
        CarBrand::create(['name' => 'Mazda', 'name_ru' => 'Мазда', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Mazda')]);
        CarBrand::create(['name' => 'McLaren', 'name_ru' => 'Макларен', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('McLaren')]);
        CarBrand::create(['name' => 'Mega', 'name_ru' => 'Мега', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Mega')]);
        CarBrand::create(['name' => 'Mercedes-Benz', 'name_ru' => 'Мерседес Бенц', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Mercedes-Benz')]);
        CarBrand::create(['name' => 'Mercury', 'name_ru' => 'Меркурий', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Mercury')]);
        CarBrand::create(['name' => 'Metrocab', 'name_ru' => 'Metrocab', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Metrocab')]);
        CarBrand::create(['name' => 'MG', 'name_ru' => 'MG', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('MG')]);
        CarBrand::create(['name' => 'Microcar', 'name_ru' => 'Microcar', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Microcar')]);
        CarBrand::create(['name' => 'Minelli', 'name_ru' => 'Минелли', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Minelli')]);
        CarBrand::create(['name' => 'MINI', 'name_ru' => 'МИНИ', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('MINI')]);
        CarBrand::create(['name' => 'Mitsubishi', 'name_ru' => 'Митсубиси', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Mitsubishi')]);
        CarBrand::create(['name' => 'Mitsuoka', 'name_ru' => 'Mitsuoka', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Mitsuoka')]);
        CarBrand::create(['name' => 'Morgan', 'name_ru' => 'Морган', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Morgan')]);
        CarBrand::create(['name' => 'Morris', 'name_ru' => 'Моррис', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Morris')]);
        CarBrand::create(['name' => 'Nash', 'name_ru' => 'Nash', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Nash')]);
        CarBrand::create(['name' => 'Nissan', 'name_ru' => 'Нисан', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Nissan')]);
        CarBrand::create(['name' => 'Noble', 'name_ru' => 'Нобле', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Noble')]);
        CarBrand::create(['name' => 'Oldsmobile', 'name_ru' => 'Oldsmobile', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Oldsmobile')]);
        CarBrand::create(['name' => 'Opel', 'name_ru' => 'Опел', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Opel')]);
        CarBrand::create(['name' => 'Osca', 'name_ru' => 'Osca', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Osca')]);
        CarBrand::create(['name' => 'Packard', 'name_ru' => 'Packard', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Packard')]);
        CarBrand::create(['name' => 'Pagani', 'name_ru' => 'Пагани', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Pagani')]);
        CarBrand::create(['name' => 'Panoz', 'name_ru' => 'Panoz', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Panoz')]);
        CarBrand::create(['name' => 'Perodua', 'name_ru' => 'Perodua', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Perodua')]);
        CarBrand::create(['name' => 'Peugeot', 'name_ru' => 'Пежот', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Peugeot')]);
        CarBrand::create(['name' => 'PGO', 'name_ru' => 'PGO', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('PGO')]);
        CarBrand::create(['name' => 'Piaggio', 'name_ru' => 'Piaggio', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Piaggio')]);
        CarBrand::create(['name' => 'Plymouth', 'name_ru' => 'Плимут', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Plymouth')]);
        CarBrand::create(['name' => 'Pontiac', 'name_ru' => 'Понтиак', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Pontiac')]);
        CarBrand::create(['name' => 'Porsche', 'name_ru' => 'Порше', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Porsche')]);
        CarBrand::create(['name' => 'Premier', 'name_ru' => 'Премьер', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Premier')]);
        CarBrand::create(['name' => 'Proton', 'name_ru' => 'Протон', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Proton')]);
        CarBrand::create(['name' => 'PUCH', 'name_ru' => 'PUCH', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('PUCH')]);
        CarBrand::create(['name' => 'Puma', 'name_ru' => 'Пума', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Puma')]);
        CarBrand::create(['name' => 'Qoros', 'name_ru' => 'Qoros', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Qoros')]);
        CarBrand::create(['name' => 'Qvale', 'name_ru' => 'Qvale', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Qvale')]);
        CarBrand::create(['name' => 'Rambler', 'name_ru' => 'Рамблер', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Rambler')]);
        CarBrand::create(['name' => 'Ravon', 'name_ru' => 'Равон', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Ravon')]);
        CarBrand::create(['name' => 'Reliant', 'name_ru' => 'Релиант', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Reliant')]);
        CarBrand::create(['name' => 'Renaissance', 'name_ru' => 'Renaissance', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Renaissance')]);
        CarBrand::create(['name' => 'Renault', 'name_ru' => 'Рено', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Renault')]);
        CarBrand::create(['name' => 'Renault Samsung', 'name_ru' => 'Рено Самсунг', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Renault Samsung')]);
        CarBrand::create(['name' => 'Rezvani', 'name_ru' => 'Резвани', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Rezvani')]);
        CarBrand::create(['name' => 'Rimac', 'name_ru' => 'Римак', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Rimac')]);
        CarBrand::create(['name' => 'Rinspeed', 'name_ru' => 'Rinspeed', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Rinspeed')]);
        CarBrand::create(['name' => 'Rolls-Royce', 'name_ru' => 'Ролс Ройс', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Rolls-Royce')]);
        CarBrand::create(['name' => 'Ronart', 'name_ru' => 'Ronart', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Ronart')]);
        CarBrand::create(['name' => 'Rover', 'name_ru' => 'Ровер', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Rover')]);
        CarBrand::create(['name' => 'Saab', 'name_ru' => 'Saab', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Saab')]);
        CarBrand::create(['name' => 'Saipa', 'name_ru' => 'Saipa', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Saipa')]);
        CarBrand::create(['name' => 'Saleen', 'name_ru' => 'Saleen', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Saleen')]);
        CarBrand::create(['name' => 'Santana', 'name_ru' => 'Сантана', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Santana')]);
        CarBrand::create(['name' => 'Saturn', 'name_ru' => 'Сатурн', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Saturn')]);
        CarBrand::create(['name' => 'Scion', 'name_ru' => 'Скион', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Scion')]);
        CarBrand::create(['name' => 'SEAT', 'name_ru' => 'Сиат', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('SEAT')]);
        CarBrand::create(['name' => 'Shanghai Maple', 'name_ru' => 'Шанхайский Мапли', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Shanghai Maple')]);
        CarBrand::create(['name' => 'ShuangHuan', 'name_ru' => 'Shuanghuan', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('ShuangHuan')]);
        CarBrand::create(['name' => 'Simca', 'name_ru' => 'Simca', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Simca')]);
        CarBrand::create(['name' => 'Skoda', 'name_ru' => 'Шкода', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Skoda')]);
        CarBrand::create(['name' => 'Smart', 'name_ru' => 'Смарт', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Smart')]);
        CarBrand::create(['name' => 'Soueast', 'name_ru' => 'Soueast', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Soueast')]);
        CarBrand::create(['name' => 'Spectre', 'name_ru' => 'Спектра', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Spectre')]);
        CarBrand::create(['name' => 'Spyker', 'name_ru' => 'Спикер', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Spyker')]);
        CarBrand::create(['name' => 'SsangYong', 'name_ru' => 'SsangYong', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('SsangYong')]);
        CarBrand::create(['name' => 'Steyr', 'name_ru' => 'Steyr', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Steyr')]);
        CarBrand::create(['name' => 'Studebaker', 'name_ru' => 'Studebaker', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Studebaker')]);
        CarBrand::create(['name' => 'Subaru', 'name_ru' => 'Субару', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Subaru')]);
        CarBrand::create(['name' => 'Suzuki', 'name_ru' => 'Сузуки', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Suzuki')]);
        CarBrand::create(['name' => 'Talbot', 'name_ru' => 'Talbot', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Talbot')]);
        CarBrand::create(['name' => 'TATA', 'name_ru' => 'TATA', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('TATA')]);
        CarBrand::create(['name' => 'Tatra', 'name_ru' => 'Татра', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Tatra')]);
        CarBrand::create(['name' => 'Tazzari', 'name_ru' => 'Tazzari', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Tazzari')]);
        CarBrand::create(['name' => 'Tesla', 'name_ru' => 'Тесла', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Tesla')]);
        CarBrand::create(['name' => 'Think', 'name_ru' => 'Финк', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Think')]);
        CarBrand::create(['name' => 'Tianma', 'name_ru' => 'Tianma', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Tianma')]);
        CarBrand::create(['name' => 'Tianye', 'name_ru' => 'Tianye', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Tianye')]);
        CarBrand::create(['name' => 'Tofas', 'name_ru' => 'Tofas', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Tofas')]);
        CarBrand::create(['name' => 'Toyota', 'name_ru' => 'Тойота', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Toyota')]);
        CarBrand::create(['name' => 'Trabant', 'name_ru' => 'Trabant', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Trabant')]);
        CarBrand::create(['name' => 'Tramontana', 'name_ru' => 'Tramontana', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Tramontana')]);
        CarBrand::create(['name' => 'Triumph', 'name_ru' => 'Триумф', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Triumph')]);
        CarBrand::create(['name' => 'TVR', 'name_ru' => 'TVR', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('TVR')]);
        CarBrand::create(['name' => 'Ultima', 'name_ru' => 'Ултима', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Ultima')]);
        CarBrand::create(['name' => 'Vauxhall', 'name_ru' => 'Vauxhall', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Vauxhall')]);
        CarBrand::create(['name' => 'Vector', 'name_ru' => 'Вектор', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Vector')]);
        CarBrand::create(['name' => 'Venturi', 'name_ru' => 'Venturi', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Venturi')]);
        CarBrand::create(['name' => 'Volkswagen', 'name_ru' => 'Фольцваген', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Volkswagen')]);
        CarBrand::create(['name' => 'Volvo', 'name_ru' => 'Вольво', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Volvo')]);
        CarBrand::create(['name' => 'Vortex', 'name_ru' => 'Вортекс', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Vortex')]);
        CarBrand::create(['name' => 'W Motors', 'name_ru' => 'W Motors', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('W Motors')]);
        CarBrand::create(['name' => 'Wanderer', 'name_ru' => 'Вандер', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Wanderer')]);
        CarBrand::create(['name' => 'Wartburg', 'name_ru' => 'Wartburg', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Wartburg')]);
        CarBrand::create(['name' => 'Westfield', 'name_ru' => 'Westfield', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Westfield')]);
        CarBrand::create(['name' => 'Wiesmann', 'name_ru' => 'Wiesmann', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Wiesmann')]);
        CarBrand::create(['name' => 'Willys', 'name_ru' => 'Willys', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Willys')]);
        CarBrand::create(['name' => 'Xin Kai', 'name_ru' => 'Синь Кай', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Xin Kai')]);
        CarBrand::create(['name' => 'Zastava', 'name_ru' => 'Застава', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Zastava')]);
        CarBrand::create(['name' => 'Zenos', 'name_ru' => 'Зенос', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Zenos')]);
        CarBrand::create(['name' => 'Zenvo', 'name_ru' => 'Zenvo', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Zenvo')]);
        CarBrand::create(['name' => 'Zibar', 'name_ru' => 'Zibar', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Zibar')]);
        CarBrand::create(['name' => 'Zotye', 'name_ru' => 'Zotye', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Zotye')]);
        CarBrand::create(['name' => 'ZX', 'name_ru' => 'ZX', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('ZX')]);
        CarBrand::create(['name' => 'Автокам', 'name_ru' => 'Автокам', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Автокам')]);
        CarBrand::create(['name' => 'ГАЗ', 'name_ru' => 'ГАЗ', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('ГАЗ')]);
        CarBrand::create(['name' => 'Ё-мобиль', 'name_ru' => 'Ё-мобиль', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Ё-мобиль')]);
        CarBrand::create(['name' => 'ЗАЗ', 'name_ru' => 'ЗАЗ', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('ЗАЗ')]);
        CarBrand::create(['name' => 'ЗИЛ', 'name_ru' => 'ЗИЛ', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('ЗИЛ')]);
        CarBrand::create(['name' => 'ЗиС', 'name_ru' => 'ЗиС', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('ЗиС')]);
        CarBrand::create(['name' => 'ИЖ', 'name_ru' => 'ИЖ', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('ИЖ')]);
        CarBrand::create(['name' => 'Канонир', 'name_ru' => 'Канонир', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Канонир')]);
        CarBrand::create(['name' => 'Комбат', 'name_ru' => 'Комбат', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Комбат')]);
        CarBrand::create(['name' => 'ЛуАЗ', 'name_ru' => 'ЛуАЗ', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('ЛуАЗ')]);
        CarBrand::create(['name' => 'Москвич', 'name_ru' => 'Москвич', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('Москвич')]);
        CarBrand::create(['name' => 'СМЗ', 'name_ru' => 'СМЗ', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('СМЗ')]);
        CarBrand::create(['name' => 'ТагАЗ', 'name_ru' => 'ТагАЗ', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('ТагАЗ')]);
        CarBrand::create(['name' => 'УАЗ', 'name_ru' => 'УАЗ', 'status' => 'active', 'author_id' => 1, 'slug' => Str::slug('УАЗ')]);

    }
}
